### ISSUE TITLE
Irc port has to be 6697 for a ssl connection 

### ISSUE THREAD

**Issue by hhl** [siduction/siduction-irc#1]
[02:25] <siducer727> in siduction-irc must be used 6697 port instead of 6667?
[02:26] <siducer727> using default 6667 I have a ssl error
[02:26] <siducer727> error:0A0000C6:SSL routines::packet length too long)
[02:26] <siducer727> thank you!

As in oftc explained, it is right, it should be port 6697.

In line 22 there is port 6667 declared, this should be changed, as it is recommended to use a ssl connection for IRC.

**Comment by ak-li** [comment]
also change needed in 
/etc/default/distro line 14

**Comment by hhl** [comment]
@ak-li 
I don't understand!

Line 14 is part of the copyright.

Do you reference to this, starting with line 18 and following?
https://github.com/siduction/siduction-irc/blob/a1bf16c12880b69afcfc2d72ca4620710a46e0ce/siduction-irc#L18

If so, what has to be changed?
If so, please look at the pull request.  #2

/etc/default/distro line 14 will be overwritten with the right parameters from this script.

**Comment by ak-li** [comment]
@hhl 

The variable is overwritten in 'siduction-irc' for functional safety. But why should we enter an incorrect value for the same variable in the '/etc/default/distro' file?
I think we should change that.
